-- Create pitchers table
CREATE TABLE IF NOT EXISTS pitchers (
    player_id INTEGER PRIMARY KEY,
    player_name VARCHAR,
    p_throws VARCHAR
);

-- Create batters table
CREATE TABLE IF NOT EXISTS batters (
    player_id INTEGER PRIMARY KEY,
    player_name VARCHAR,
    stand VARCHAR
);

-- MLB Statcast Table
CREATE TABLE IF NOT EXISTS statcast_major (
    game_pk INTEGER,
    game_date DATE,
    pitch_type VARCHAR,
    release_speed DOUBLE,
    release_pos_x DOUBLE,
    release_pos_z DOUBLE,
    batter INTEGER,
    pitcher INTEGER,
    events VARCHAR,
    description VARCHAR,
    zone INTEGER,
    stand VARCHAR,
    p_throws VARCHAR,
    home_team VARCHAR,
    away_team VARCHAR,
    hit_location INTEGER,
    bb_type VARCHAR,
    balls INTEGER,
    strikes INTEGER,
    game_year INTEGER,
    pfx_x DOUBLE,
    pfx_z DOUBLE,
    plate_x DOUBLE,
    plate_z DOUBLE,
    outs_when_up INTEGER,
    inning INTEGER,
    inning_topbot VARCHAR,
    hc_x DOUBLE,
    hc_y DOUBLE,
    vx0 DOUBLE,
    vy0 DOUBLE,
    vz0 DOUBLE,
    ax DOUBLE,
    ay DOUBLE,
    az DOUBLE,
    sz_top DOUBLE,
    sz_bot DOUBLE,
    hit_distance_sc DOUBLE,
    launch_speed DOUBLE,
    launch_angle DOUBLE,
    effective_speed DOUBLE,
    release_spin_rate DOUBLE,
    release_extension DOUBLE,
    release_pos_y DOUBLE,
    estimated_ba_using_speedangle DOUBLE,
    estimated_woba_using_speedangle DOUBLE,
    estimated_slg_using_speedangle DOUBLE,
    estimated_iso_using_speedangle DOUBLE,
    phi DOUBLE,
    pitch_name VARCHAR,
    post_away_score INTEGER,
    post_home_score INTEGER,
    if_fielding_alignment VARCHAR,
    of_fielding_alignment VARCHAR,
    spin_axis INTEGER,
    delta_home_win_exp DOUBLE,
    delta_run_exp DOUBLE,
    bat_speed DOUBLE,
    swing_length DOUBLE,
    home_win_exp DOUBLE,
    api_break_z_with_gravity DOUBLE,
    api_break_x_batter_in DOUBLE,
    arm_angle DOUBLE,
    attack_angle DOUBLE,
    attack_direction DOUBLE,
    swing_path_tilt DOUBLE,
    intercept_ball_minus_batter_pos_x_inches DOUBLE,
    intercept_ball_minus_batter_pos_y_inches DOUBLE,
    HA_factor DOUBLE,
    HA_Adj_estimated_xISO DOUBLE,
    is_zone INTEGER,
    pitch_bucket VARCHAR,
    pitch_subtype VARCHAR,
    FOREIGN KEY (batter) REFERENCES batters(player_id),
    FOREIGN KEY (pitcher) REFERENCES pitchers(player_id)
);

-- Minor League Statcast Table
CREATE TABLE IF NOT EXISTS statcast_minor (
    game_pk INTEGER,
    game_date DATE,
    pitch_type VARCHAR,
    release_speed DOUBLE,
    release_pos_x DOUBLE,
    release_pos_z DOUBLE,
    batter INTEGER,
    pitcher INTEGER,
    events VARCHAR,
    description VARCHAR,
    zone INTEGER,
    stand VARCHAR,
    p_throws VARCHAR,
    home_team VARCHAR,
    away_team VARCHAR,
    hit_location INTEGER,
    bb_type VARCHAR,
    balls INTEGER,
    strikes INTEGER,
    game_year INTEGER,
    pfx_x DOUBLE,
    pfx_z DOUBLE,
    plate_x DOUBLE,
    plate_z DOUBLE,
    outs_when_up INTEGER,
    inning INTEGER,
    inning_topbot VARCHAR,
    hc_x DOUBLE,
    hc_y DOUBLE,
    vx0 DOUBLE,
    vy0 DOUBLE,
    vz0 DOUBLE,
    ax DOUBLE,
    ay DOUBLE,
    az DOUBLE,
    sz_top DOUBLE,
    sz_bot DOUBLE,
    hit_distance_sc DOUBLE,
    launch_speed DOUBLE,
    launch_angle DOUBLE,
    effective_speed DOUBLE,
    release_spin_rate DOUBLE,
    release_extension DOUBLE,
    release_pos_y DOUBLE,
    estimated_ba_using_speedangle DOUBLE,
    estimated_woba_using_speedangle DOUBLE,
    estimated_slg_using_speedangle DOUBLE,
    estimated_iso_using_speedangle DOUBLE,
    phi DOUBLE,
    pitch_name VARCHAR,
    post_away_score INTEGER,
    post_home_score INTEGER,
    if_fielding_alignment VARCHAR,
    of_fielding_alignment VARCHAR,
    spin_axis INTEGER,
    delta_home_win_exp DOUBLE,
    delta_run_exp DOUBLE,
    bat_speed DOUBLE,
    swing_length DOUBLE,
    home_win_exp DOUBLE,
    api_break_z_with_gravity DOUBLE,
    api_break_x_batter_in DOUBLE,
    arm_angle DOUBLE,
    attack_angle DOUBLE,
    attack_direction DOUBLE,
    swing_path_tilt DOUBLE,
    intercept_ball_minus_batter_pos_x_inches DOUBLE,
    intercept_ball_minus_batter_pos_y_inches DOUBLE,
    HA_factor DOUBLE,
    HA_Adj_estimated_xISO DOUBLE,
    is_zone INTEGER,
    pitch_bucket VARCHAR,
    pitch_subtype VARCHAR,
);

-- Create games table
CREATE TABLE IF NOT EXISTS start_game (
    game_pk INTEGER PRIMARY KEY,
    game_date DATE,
    home_team VARCHAR,
    away_team VARCHAR,
    home_starting_pitcher INTEGER,
    away_starting_pitcher INTEGER,
    home_batter_1 INTEGER,
    home_batter_2 INTEGER,
    home_batter_3 INTEGER,
    home_batter_4 INTEGER,
    home_batter_5 INTEGER,
    home_batter_6 INTEGER,
    home_batter_7 INTEGER,
    home_batter_8 INTEGER,
    home_batter_9 INTEGER,
    away_batter_1 INTEGER,
    away_batter_2 INTEGER,
    away_batter_3 INTEGER,
    away_batter_4 INTEGER,
    away_batter_5 INTEGER,
    away_batter_6 INTEGER,
    away_batter_7 INTEGER,
    away_batter_8 INTEGER,
    away_batter_9 INTEGER,
    FOREIGN KEY (home_starting_pitcher) REFERENCES pitchers(player_id),
    FOREIGN KEY (away_starting_pitcher) REFERENCES pitchers(player_id)
); 